const Images = {
    icon_ub_creditcard_amex: require("./ub__creditcard_amex.png"),
    icon_ub_creditcard_diners: require("./ub__creditcard_diners.png"),
    icon_ub_creditcard_discover: require("./ub__creditcard_discover.png"),
    icon_ub_creditcard_jcb: require("./ub__creditcard_jcb.png"),
    icon_ub_creditcard_mastercard: require("./ub__creditcard_mastercard.png"),
    icon_ub_creditcard_visa: require("./ub__creditcard_visa.png"),
    icon_ub_creditcard_elo: require("./elo.png"),
    terra_card: require('./cartao_terra.png'),
    icon_pix: require("./pix.png"),
    icon_pix_bc: require("./pix_bc.png"),
    icon_remove: require("./trash-simple.png"),
    icon_money: require("./money.png"),
    machine: require("./machine.png"),
    bitcoin: require("./machine.png"),
    balance: require("./balance.png"),
    icon_pix: require("./pix.png"),
    icon_bank_profile: require('./bank-profile.png'),
    warning: require('./warning.png'),
    iconCard: require('./paymentIcons/card.png'),
    iconcryptoCurrency: require('./paymentIcons/cryptocurrency.png'),
    iconMachine: require('./paymentIcons/machine.png'),
    iconMoney: require('./paymentIcons/money.png'),
    iconCarto: require('./paymentIcons/carto.png'),
    payment_balance: require("./paymentIcons/baseline-account-balance.png"),
    payment_billing: require("./paymentIcons/voucher.png"),
};

export default Images;
